use_frameworks!

platform :ios, '9.0'

target 'MediatorTarget_Example' do
  pod 'MediatorTarget', :path => '../'

  target 'MediatorTarget_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
